apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: 2umm3r/summerinfo-game
          env:
            - name: MONGO_URI
              value : 'mongodb://game-mongo-svc:27017/game'
            - name: JWT_KEY
              value: 5854bd9a65710edd5b9ba2f161de0c30
          readinessProbe:
            httpGet:
              path: /api/game/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1 
kind: Service
metadata:
  name: game-svc
spec:
  selector:
    app: game
  ports:
    - name: game
      protocol: TCP
      port: 3000
      targetPort: 3000
