apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-peer-discovery-rbac
subjects:
  - kind: ServiceAccount
    name: rabbitmq-sa
roleRef:
  kind: Role
  name: rabbitmq-peer-discovery-rbac
  apiGroup: rbac.authorization.k8s.io
