apiVersion: v1 
kind: ConfigMap
metadata:
  name: auth-postgres-initdb
  labels:
    app: auth-postgres
data:
  init.sql: |
    DROP TABLE IF EXISTS "user";
    
    CREATE TABLE "users" (
      "id" SERIAL NOT NULL PRIMARY KEY,
      "uuid" TEXT NOT NULL,
      "email" TEXT NOT NULL,
      "username" TEXT NOT NULL,
      "password" TEXT NOT NULL
    );

    CREATE UNIQUE INDEX idx_user_email ON "user" ("email");
    CREATE UNIQUE INDEX idx_user_username ON "user" ("username");
