apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-postgres-secret
  labels:
    app: auth-postgres
data:
  POSTGRES_DB: auth_db
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: 192ca54baf44ad83d0071a19feedac2d
