apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-volume-claim
  labels:
    app: auth-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi