apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
  labels:
    app: auth-mongo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi