apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mongo-pv
  labels:
    app: auth-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/mongodb
  persistentVolumeReclaimPolicy: Retain